on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x hooks/*
      - run: ./hooks/pre_build
      - run: ./hooks/build
      - run: ./hooks/push